name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: get the codes
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: build the project
        run: tsc --build
      - name: create .env
        run: |
          touch .env
          echo "${{secrets.PROD_ENV_FILE}}" > .env
